version: '3.7'
services:
  app:
    build: ./server
    container_name: nodejs-app
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    # Publicly accessible service
    labels:
      - "render.com/web"

  live-streaming:
    build: ./Live-Streaming-Service
    container_name: live-stream
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - redis
      - app
    volumes:
      - ./Live-Streaming-Service:/app
    # Publicly accessible service
    labels:
      - "render.com/web"

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data

  transcoder:
    build: ./Video-Transcoding-Service
    container_name: video-transcoder
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - ./Video-Transcoding-Service/.env
    depends_on:
      - redis
    volumes:
      - ./Video-Transcoding-Service:/app

volumes:
  mongo_data:
  redis_data:
